package com.pingme.shared.events;

public enum EventType {
    MEMBER_KICKED,
    MEMBER_ROLE_UPDATED,
    MEMBER_ADDED,
    DETAILS_UPDATED,
    CHAT_CREATED,
    CHAT_DELETED,
    MESSAGE_DELETED,
    MESSAGE_EDITED,
    CONTACT_RECEIVED,
    CONTACT_ACCEPTED,
    CONTACT_REJECTED,
    CONTACT_CANCEL,
    CONTACT_DELETED
}